server:
  port: 8082
spring:
  datasource:
    password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:25432}/users_database
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
